name: midibinds

version: 0.1.0.0
license:             MIT
license-file:        LICENSE
author:              Akshay Nair
maintainer:          phenax5@gmail.com
build-type:          Simple

ghc-options:
  -Wall
  -Wdefault
  -Wextra
  -Wno-unused-do-bind
  -fwarn-tabs
  -Wname-shadowing

dependencies:
  - base
  - process
  - PortMidi
  - PortMidi-simple
  - mtl
  - containers
  - optparse-simple

default-extensions:
  - LambdaCase
  - NamedFieldPuns
  - FlexibleContexts

library:
  source-dirs: src/

executables:
  midibinds:
    main: Main.hs
    source-dirs:
      - src/
