name: midi-keybindings

# cabal-version: 2.0

version: 0.1.0.0
license:             MIT
license-file:        LICENSE
author:              Akshay Nair
maintainer:          phenax5@gmail.com
build-type:          Simple

ghc-options:
  -Wall
  -Wdefault
  -Wextra
  -Wno-unused-do-bind
  -fwarn-tabs
  -Wname-shadowing

dependencies:
  - base
  - process
  - PortMidi
  - PortMidi-simple
  - mtl
  - containers
  - optparse-simple
  # - hint
  # - text
  # - transformers

default-extensions:
  - LambdaCase
  - NamedFieldPuns
  - FlexibleContexts
#   - QuasiQuotes
#   - TupleSections
#   - FlexibleInstances
#   - TypeSynonymInstances
#   - DataKinds
#   - KindSignatures

library:
  source-dirs: src/

executables:
  midibind:
    main: Main.hs
    source-dirs:
      - src/
